# Generated by Django 5.1.5 on 2025-02-19 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameapr', models.CharField(max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('presidente', models.CharField(max_length=100, null=True)),
                ('secretario', models.CharField(max_length=100, null=True)),
                ('tesorero', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('twitter', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('socios', models.IntegerField(max_length=5, null=True)),
                ('horario', models.CharField(max_length=100, null=True)),
                ('mapa', models.CharField(max_length=100, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='apr')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('ssr_apr', models.CharField(max_length=100, null=True)),
                ('cargo_apr', models.CharField(max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100, null=True)),
                ('cantidad', models.IntegerField(max_length=4, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('radio', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
