# Generated by Django 5.2.4 on 2025-07-24 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_email_apr_correo_rename_email_contacto_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True, verbose_name='Título')),
                ('sub_titulo', models.CharField(max_length=100, null=True, verbose_name='Subtítulo')),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('creador', models.CharField(max_length=100, null=True, verbose_name='Creador')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('contenido', models.TextField(null=True, verbose_name='Contenido')),
                ('id_yt', models.CharField(max_length=100, null=True, verbose_name='Link Youtube')),
                ('check_yt', models.BooleanField(default=False, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenTestimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='testimonios', verbose_name='Imagen')),
                ('testimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.testimonio')),
            ],
        ),
    ]
