# Generated by Django 5.2.4 on 2025-07-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_testimonio_imagentestimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='testimonios', verbose_name='Imagen'),
        ),
    ]
