# Generated by Django 5.2.4 on 2025-07-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_testimonio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='Palabras Clave'),
        ),
    ]
