# Generated by Django 5.2.4 on 2025-07-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_testimonio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonio',
            name='imagen',
        ),
    ]
