# Generated by Django 5.1.2 on 2025-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_apr_comuna_alter_apr_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
